### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by weisuogou** [ixmilia/dwg#1]

**Comment by weisuogou** [comment]
my dear  friend ,i  found your project ,i am very happy to see this great pro.
can this project complie  ok?
i  use  visual stuido 2017 to build it ,but  it come to  many  errors..
help~┭┮﹏┭┮

**Comment by mattia589** [comment]
Good evening, i have searched in nuGet the ixmilia dwg library without success. is it available? How can i use your portable library? I'm not able to compile the project and I have tried to start the Generator project but no args error appears . The generate code script does not give a positive feedback. Thanks in advance for you feedback.

**Comment by kwkoranda** [comment]
@mattia589 Start the Generator project debug mode with command line arguments - see the attached photo from VS 2022. The argument you pass in should be the destination folder for the generated class files. I simply put them in a folder called "Generated" within the IxMilia.Dwg project and the Dwg project builds. 


![image](https://user-images.githubusercontent.com/112811569/194182049-ebacd844-61af-4fa1-9b2e-ab8d8a596258.png)
