### ISSUE TITLE
Library usage

### ISSUE THREAD

**Issue by mattia589** [ixmilia/dwg#6]
Good evening, i have searched in nuGet the ixmilia dwg library without success. is it available? How can i use your portable library? I'm not able to compile the project and I have tried to start the Generator project but no args error appears . The generate code script does not give a positive feedback. Thanks in advance for you feedback.

**Comment by brettfo** [comment]
This library currently isn't ready for a proper NuGet release, but if you'd like to build it yourself you should be able to just run the `.\build-and-test.ps1` script in the root in PowerShell 7.  I'll update the README with this info.
